language: node_js
node_js: stable

compiler: gcc
sudo: false

env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI=true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.7
      - g++-4.7
      - gcc-4.9
      - g++-4.9

os:
  - linux
#  - osx


before_install:
  - echo $TRAVIS_NODE_VERSION
  - npm config set python `which python`
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    if [[ $(node -v) =~ v[1-9][0-9] ]]; then
    export CC="gcc-4.9";
    export CXX="g++-4.9";
    export LINK="gcc-4.9";
    export LINKXX="g++-4.9";
    else
    export CC="gcc-4.7";
    export CXX="g++-4.7";
    export LINK="gcc-4.7";
    export LINKXX="g++-4.7";
    fi
    fi
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

before_script:
  - npm install

branches:
  only: master

notifications:
  email: true

script:
  - npm run build

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
