language: node_js
node_js: stable

sudo: false

before_script:
  - npm install

branches:
  only: master

notifications:
  email: true

script:
  - npm run build

cache:
  directories:
    - node_modules
